### ISSUE TITLE
Unable to compile on ubuntu 14.04 32 bits

### ISSUE THREAD

**Issue by grm** [lucasjones/cpuminer-multi#8]
hello,

 I have succes compiling this miner on several x86-64 ubuntu computers but i can't manage to compile it on a ubuntu 14.04 computer.
It seems to fail at then end of the compilation process. with the following message.
So i am trying to compile it on an ubuntu 14.04 32 bits.

```
mv -f .deps/minerd-x11.Tpo .deps/minerd-x11.Po
mv -f .deps/minerd-cryptonight.Tpo .deps/minerd-cryptonight.Po
mv -f .deps/minerd-sha2.Tpo .deps/minerd-sha2.Po
mv -f .deps/minerd-c_skein.Tpo .deps/minerd-c_skein.Po
gcc -std=gnu99  -O3 -pthread  -o minerd minerd-cpu-miner.o minerd-util.o minerd-sha2.o minerd-scrypt.o minerd-keccak.o minerd-heavy.o minerd-quark.o minerd-skein.o minerd-ink.o minerd-blake.o minerd-cryptonight.o minerd-x11.o minerd-sph_keccak.o minerd-sph_hefty1.o minerd-sph_groestl.o minerd-sph_skein.o minerd-sph_bmw.o minerd-sph_jh.o minerd-sph_shavite.o minerd-sph_blake.o minerd-sph_luffa.o minerd-sph_cubehash.o minerd-sph_simd.o minerd-sph_echo.o minerd-oaes_lib.o minerd-c_keccak.o minerd-c_groestl.o minerd-c_blake256.o minerd-c_jh.o minerd-c_skein.o minerd-hash.o minerd-aesb.o minerd-sha2-x86.o minerd-scrypt-x86.o   -L/usr/lib/i386-linux-gnu -lcurl compat/jansson/libjansson.a -lpthread  -lcrypto
minerd-cryptonight.o: In function `cryptonight_hash_ctx_aes_ni':
cryptonight.c:(.text+0xdb3): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0xdce): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0xde9): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0xe04): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0xe1f): undefined reference to `fast_aesb_pseudo_round_mut'
minerd-cryptonight.o:cryptonight.c:(.text+0xe3a): more undefined references to `fast_aesb_pseudo_round_mut' follow
minerd-cryptonight.o: In function `cryptonight_hash_ctx_aes_ni':
cryptonight.c:(.text+0xfa7): undefined reference to `fast_aesb_single_round'
cryptonight.c:(.text+0x119e): undefined reference to `fast_aesb_single_round'
cryptonight.c:(.text+0x140a): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0x1449): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0x1488): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0x14c7): undefined reference to `fast_aesb_pseudo_round_mut'
cryptonight.c:(.text+0x1506): undefined reference to `fast_aesb_pseudo_round_mut'
minerd-cryptonight.o:cryptonight.c:(.text+0x1545): more undefined references to `fast_aesb_pseudo_round_mut' follow
collect2: error: ld returned 1 exit status
```

The only reference to fast_aesb_single_round i could find is in the file aesb-x64.S file which looks like  a file dedicated to X86-64 systems :

```
$ grep -ri fast_aesb_single_round .
./cryptonight.c:extern int fast_aesb_single_round(const uint8_t *in, uint8_t*out, const uint8_t *expandedKey);
./cryptonight.c:        fast_aesb_single_round(&ctx->long_state[j], ctx->c, ctx->a);
./cryptonight.c:        fast_aesb_single_round(&ctx->long_state[j], ctx->b, ctx->a);
./aesb-x64.S:    .globl fast_aesb_single_round
./aesb-x64.S:    .globl _fast_aesb_single_round
./aesb-x64.S:fast_aesb_single_round:
./aesb-x64.S:_fast_aesb_single_round:
Binary file ./minerd-cryptonight.o matches
```

I can provide any information you need.
Thx for your help !
